### ISSUE TITLE
STYTJ02YM not supported?

### ISSUE THREAD

**Issue by marianbezeg** [nergal/homeassistant-vacuum-viomi#22]
Hello,

looks like that this type is not supported under your integration ?
Model: viomi.vacuum.v8 STYTJ02YM 
I've tried latest version, beta as well but its not working.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 246, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 175, in async_create_setup_task
    return platform.async_setup_platform(  # type: ignore
TypeError: async_setup_platform() takes 3 positional arguments but 4 were given

When I am trying to set up via Integration:
Incomplete information to setup device, no host or token supplied
![image](https://user-images.githubusercontent.com/25847353/151545199-52de163a-0cad-4f66-823d-aa088df32539.png)

**Comment by nergal** [comment]
Hello @marianbezeg , looks like you're using the v0.0.4-beta build which is broken right now. You can switch to the stable v0.0.3 which won't rise the error that shown up in the log that you've shared

**Comment by snp88** [comment]
I can confirm that STYTJ02YM  work on v0.0.3 beside some minor issues;)
