### ISSUE TITLE
Fatal error after update to 0.0.4 Integation don't start at all

### ISSUE THREAD

**Issue by snp88** [nergal/homeassistant-vacuum-viomi#23]
Hi 
After update to 0.0.4 version integration don't work at all after the reboot 
My HA version is 2022.2.0
bellow screenshot with error 
![image](https://user-images.githubusercontent.com/46537540/152547708-15ec72f2-e58c-422d-be92-fea637a8e8ba.png)

**Comment by nergal** [comment]
Could you try to remove the integration and add it again? Apparently, an entity that has been created before the update, doesn't include a `name` field which was introduced in 0.0.4.

And let me try to fix this with care in the meantime.

**Comment by nergal** [comment]
The fix is in the master, I'm going to create a new release after the CI finish.

Will be appreciated if you'll be able to verify it.

**Comment by snp88** [comment]
ok so i competently remove configuration and integration. 
Reboot HA 
Add integration again 
reboot HA 
add configuration 

and its look like all working :)
